# docker stack deploy -c diary-stack.yml diary_stack --with-registry-auth

version: "3.9"

services:
  diary:
    image: portainer.flexpay.com.ua/diary
    ports:
      - "8081:8080"
    extra_hosts:
      - "db-server: 172.31.6.45"
      - "portainer.flexpay.com.ua: 172.31.6.45"
    deploy:
      placement:
        constraints: [node.role == worker]
#    secrets:
#      - db_name
#      - db_app_username
#      - db_app_password
    environment:
      MYSQL_DATABASE: jspDiary
      MYSQL_USER: jspdiary
      MYSQL_PASSWORD: jspdiary

#secrets:
#  db_name:
#    external: true
#  db_app_username:
#    external: true
#  db_app_password:
#    external: true
