version: '3.9'
services:
  registry:
    container_name: registry
    network_mode: "bridge"
    image:
      registry:latest
    volumes:
      - /home/kofe/portainer/docker/data:/var/lib/registry
    ports:
      - 5050:5000
    restart: unless-stopped
    deploy:
      placement:
        constraints: [node.role == manager]
